In [1]:
import pandas as pd 
fed_files = ["MORTGAGE30US.csv", "RRVRUSQ156N.csv", "CPIAUCSL.csv"]

dfs = [pd.read_csv(f, parse_dates=True, index_col=0) for f in fed_files]

In [2]:
dfs[0]

            MORTGAGE30US
DATE
1971-04-02          7.33
1971-04-09          7.31
1971-04-16          7.31
1971-04-23          7.31
1971-04-30          7.29
...                  ...
2022-07-14          5.51
2022-07-21          5.54
2022-07-28          5.30
2022-08-04          4.99
2022-08-11          5.22

[2681 rows x 1 columns]

In [3]:
dfs[1]

            RRVRUSQ156N
DATE
1956-01-01          6.2
1956-04-01          5.9
1956-07-01          6.3
1956-10-01          5.8
1957-01-01          5.3
...                 ...
2021-04-01          6.2
2021-07-01          5.8
2021-10-01          5.6
2022-01-01          5.8
2022-04-01          5.6

[266 rows x 1 columns]

In [5]:
fed_data = pd.concat(dfs, axis=1)

C:\Users\me505\AppData\Local\Temp\ipykernel_27772\2677634655.py:1: Pandas4Warning: Sorting by default when concatenating all DatetimeIndex is deprecated.  In the future, pandas will respect the default of `sort=False`. Specify `sort=True` or `sort=False` to silence this message. If you see this warnings when not directly calling concat, report a bug to pandas.
  fed_data = pd.concat(dfs, axis=1)

In [6]:
fed_data

            MORTGAGE30US  RRVRUSQ156N  CPIAUCSL
DATE
1947-01-01           NaN          NaN     21.48
1947-02-01           NaN          NaN     21.62
1947-03-01           NaN          NaN     22.00
1947-04-01           NaN          NaN     22.00
1947-05-01           NaN          NaN     21.95
...                  ...          ...       ...
2022-07-14          5.51          NaN       NaN
2022-07-21          5.54          NaN       NaN
2022-07-28          5.30          NaN       NaN
2022-08-04          4.99          NaN       NaN
2022-08-11          5.22          NaN       NaN

[3507 rows x 3 columns]

In [7]:
#no we need to fix the missing data issue
# number will stay constans till next change
fed_data = fed_data.ffill()

In [8]:
zillow_data = ["Metro_median_sale_price_uc_sfrcondo_week.csv", "Metro_zhvi_uc_sfrcondo_tier_0.33_0.67_month.csv"]
dfs = [pd.read_csv(f) for f in zillow_data]

In [9]:
dfs[0]

,RegionID,SizeRank,RegionName,RegionType,StateName,2008-02-02,2008-02-09,2008-02-16,2008-02-23,2008-03-01,...,2022-05-07,2022-05-14,2022-05-21,2022-05-28,2022-06-04,2022-06-11,2022-06-18,2022-06-25,2022-07-02,2022-07-09
0,102001,0,United States,Country,NaN,190000.0,190000.0,193000.0,189900.0,194900.0,...,369900.0,370000.0,370000.0,375000.0,375000.0,370000.0,375000.0,370000.0,370000.0,362500.0
1,394913,1,"New York, NY",Msa,NY,400000.0,418250.0,420000.0,420000.0,400000.0,...,550000.0,555000.0,550000.0,575000.0,575000.0,578000.0,590000.0,582000.0,585000.0,595000.0
2,753899,2,"Los Angeles-Long Beach-Anaheim, CA",Msa,CA,497500.0,515000.0,520000.0,525000.0,498250.0,...,914000.0,925000.0,925000.0,951000.0,950000.0,920500.0,925000.0,900000.0,900500.0,906000.0
3,394463,3,"Chicago, IL",Msa,IL,245000.0,245000.0,251000.0,255000.0,255000.0,...,315000.0,310000.0,315500.0,315000.0,330000.0,324950.0,335000.0,325000.0,325000.0,315000.0
4,394514,4,"Dallas-Fort Worth, TX",Msa,TX,144250.0,148900.0,139000.0,143700.0,145900.0,...,422000.0,430000.0,430000.0,425000.0,440000.0,425000.0,427750.0,426000.0,420000.0,420000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,394528,90,"Daytona Beach, FL",Msa,FL,NaN,170000.0,182400.0,170000.0,170000.0,...,340500.0,345000.0,327700.0,345000.0,350000.0,343250.0,359900.0,352000.0,336000.0,342990.0
80,394531,91,"Des Moines, IA",Msa,IA,138000.0,160000.0,150000.0,151750.0,154500.0,...,270000.0,285250.0,295000.0,273450.0,301000.0,290000.0,300900.0,281900.0,289250.0,280000.0
81,395006,100,"Provo, UT",Msa,UT,NaN,206000.0,215500.0,210000.0,210000.0,...,527000.0,540000.0,535000.0,552500.0,543750.0,571000.0,530300.0,569900.0,539950.0,572500.0
82,394549,104,"Durham, NC",Msa,NC,210000.0,170000.0,170500.0,197500.0,180000.0,...,456000.0,450000.0,428500.0,480000.0,465000.0,440000.0,450250.0,416000.0,465000.0,435250.0
83,394602,159,"Fort Collins, CO",Msa,CO,NaN,255000.0,205000.0,229900.0,235000.0,...,575000.0,585250.0,575000.0,550000.0,569900.0,560000.0,595000.0,550000.0,556058.0,595000.0

In [11]:
dfs = [pd.DataFrame(df.iloc[0,5:]) for df in dfs]

In [12]:
dfs[0]

                   0
2008-02-02  190000.0
2008-02-09  190000.0
2008-02-16  193000.0
2008-02-23  189900.0
2008-03-01  194900.0
...              ...
2022-06-11  370000.0
2022-06-18  375000.0
2022-06-25  370000.0
2022-07-02  370000.0
2022-07-09  362500.0

[754 rows x 1 columns]

In [13]:
#mergind collumns
for df in dfs:
    df.index = pd.to_datetime(df.index)
    df["month"] = df.index.to_period("M")

In [14]:
price_data = dfs[0].merge(dfs[1], on="month")
price_data.index = dfs[0].index
price_data

                 0_x    month            0_y
2008-02-02  190000.0  2008-02  206885.853266
2008-02-09  190000.0  2008-02  206885.853266
2008-02-16  193000.0  2008-02  206885.853266
2008-02-23  189900.0  2008-02  206885.853266
2008-03-01  194900.0  2008-03  205459.521952
...              ...      ...            ...
2022-06-11  370000.0  2022-06  357473.327397
2022-06-18  375000.0  2022-06  357473.327397
2022-06-25  370000.0  2022-06  357473.327397
2022-07-02  370000.0  2022-07  357107.271636
2022-07-09  362500.0  2022-07  357107.271636

[754 rows x 3 columns]

In [15]:
del price_data["month"]
price_data.columns = ["price", "value"]
price_data

               price          value
2008-02-02  190000.0  206885.853266
2008-02-09  190000.0  206885.853266
2008-02-16  193000.0  206885.853266
2008-02-23  189900.0  206885.853266
2008-03-01  194900.0  205459.521952
...              ...            ...
2022-06-11  370000.0  357473.327397
2022-06-18  375000.0  357473.327397
2022-06-25  370000.0  357473.327397
2022-07-02  370000.0  357107.271636
2022-07-09  362500.0  357107.271636

[754 rows x 2 columns]